version: '3.8'

services:
  # Chỉ sử dụng dịch vụ mb-api, không khởi động Traefik mới
  # Traefik đã được khởi động từ trước (container ID: be0deaa974e2)

  # MB Bank API
  mb-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: mb-api:latest
    container_name: mb-api
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/mbbank.db
      - PORT=3000
    volumes:
      - ./data:/app/data:rw
    networks:
      - traefik_web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mb-api.entrypoints=websecure"
      - "traefik.http.routers.mb-api.rule=Host(`api.${DOMAIN:-yourdomain.com}`)"
      - "traefik.http.routers.mb-api.tls=true"
      - "traefik.http.routers.mb-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.mb-api.loadbalancer.server.port=3000"
      # Bỏ comment dòng dưới nếu muốn bảo vệ API bằng Basic Auth
      # - "traefik.http.middlewares.mb-api-auth.basicauth.users=apiuser:$$apr1$$q8eZFHjF$$Fvmkk0Ev3hWvMXJKUjLys1"
      # - "traefik.http.routers.mb-api.middlewares=mb-api-auth"

networks:
  traefik_web:
    external: true